language: php

php:
  - "5.5"
  - "5.4"
  - "5.3"

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --prefer-source --no-interaction --dev
  - printf "\n" | pecl install channel://pecl.php.net/APCu-4.0.1
  - echo "extension=apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - "mysql -e 'create database agl_core_tests;'"
  - "mysql -D 'agl_core_tests' -e 'CREATE TABLE IF NOT EXISTS `comment` (`comment_id` int(10) unsigned NOT NULL AUTO_INCREMENT,`comment_date_add` datetime NOT NULL,`comment_date_update` datetime NOT NULL DEFAULT \"0000-00-00 00:00:00\",`comment_text` text NOT NULL,`user_id` varchar(255) NULL,PRIMARY KEY (`comment_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;'"
  - "mysql -D 'agl_core_tests' -e 'CREATE TABLE IF NOT EXISTS `user` (`user_id` int(10) unsigned NOT NULL AUTO_INCREMENT,`user_date_add` datetime NOT NULL,`user_date_update` datetime NOT NULL DEFAULT \"0000-00-00 00:00:00\",`user_email` varchar(255) NOT NULL,PRIMARY KEY (`user_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;'"
  - "mysql -D 'agl_core_tests' -e 'CREATE TABLE IF NOT EXISTS `session` (`session_id` int(10) unsigned NOT NULL AUTO_INCREMENT,`session_date_add` datetime NOT NULL,`session_date_update` datetime NOT NULL DEFAULT \"0000-00-00 00:00:00\",`session_data` text NOT NULL,`session_real_id` char(32) NOT NULL,`session_access` int(10) unsigned NOT NULL,PRIMARY KEY (`session_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;'"
  - "mysql -D 'agl_core_tests' -e 'INSERT INTO `user` (`user_date_add`,`user_email`) VALUES (NOW(),\"test1@agl.io\");'"
  - "mysql -D 'agl_core_tests' -e 'INSERT INTO `user` (`user_date_add`,`user_email`) VALUES (NOW(),\"test2@agl.io\");'"
  - "mysql -D 'agl_core_tests' -e 'INSERT INTO `comment` (`comment_date_add`,`comment_text`,`user_id`) VALUES (NOW(),\"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a tortor nec libero blandit tempus eu non tortor.\",1);'"
  - "mysql -D 'agl_core_tests' -e 'INSERT INTO `comment` (`comment_date_add`,`comment_text`) VALUES (NOW(),\"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec a tortor nec libero blandit tempus eu non tortor.\");'"

script: phpunit
